name: run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          token: ${{ secrets.ACTION_PAT }}
        env:
          RENOVATE_ALLOWED_COMMANDS: '["^sh \\./scripts/post-upgrade-renovate.sh$"]'
          RENOVATE_REPOSITORIES: "['a-novel/package-ui']"
          RENOVATE_DETECT_HOST_RULES_FROM_ENV: true
          RENOVATE_NPM_NPM_PKG_GITHUB_COM_TOKEN: ${{ secrets.ACTION_PAT }}
          RENOVATE_SECRETS: '{"GITHUB_TOKEN": "${{ secrets.ACTION_PAT }}"}'
          RENOVATE_CUSTOM_ENV_VARIABLES: '{"GITHUB_TOKEN": "''{{ secrets.GITHUB_TOKEN }}''"}'
          RENOVATE_PR_HOURLY_LIMIT: 0
          LOG_LEVEL: debug
